
#the yaml file gives us the human readable code
#and we have many advantage as well with that
#we can convert our application.propeties file to yaml file
#there are lot of extensions and online websites to convert that
#IN YAML the indentation is strictly followed

server:
  port: '8082'
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/arjunapp
    password: arjunroot
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
hibernate:
  transaction:
    jta:
      platform: com.atomikos.icatch.jta.hibernate4.AtomikosPlatform
welcome:
  message: 'Welcome!!!! Arjun '

